spring:
  datasource:
    url: jdbc:mysql://j9c108.p.ssafy.io:3306/bankdb?serverTimezone=UTC
    username: bank
    password: '{cipher}AQAnuSWrjs9cc7cCDbXH2iXIp26h0qU0gGlyi5+alVMBDDt+JG6LBCoSgX0k+0rrAd9cvyy8OHxewks4o32jrtNYkCDo4qucQN78fu3HJDa7jn5bl9gTnPIruazuvo2TMqDoBvliS+BZn49stC0Bfdgz0W+4ub4To6Cx5zX6sVhCATamFDt4Ls8F++xt2Iqh3SB5i1wnwG0kRNyIixhyiye2Akq7YzDfRxYQoTdt1OcbAskn3f3fe7UbIvT4fKX9vSMASO/MxF6nV+k8Dg/ctppY/J6HP7gXVo/t6ENUJ6pNcxa1gd12ymsyf3uf015Y8zWkBmPHVQ7Qi3MFMqfgsDv3ihWIYfqK66DcaO7Md80F1PN2qkVCWSbgq8gktAaCilI='
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 'update' is for development. Use 'validate' for production.
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


# jutopia-network의 apigateway ip address로 변경
gateway:
  ip: 172.18.0.3