spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9c108.p.ssafy.io:3306/jutopia?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # url: jdbc:mysql://mysql-master:3306/jutopia?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: '{cipher}AQAoXMrKBup6aaYCg0wU+tDBVcvTpIg42opco+oqRNUrL1UdnWNDjPBE2tvIt17xYt4QkJGzoXEHG7J+mSi4Nv3ir3Y8t0C3PSPwzP44WULcM3Ni35nW9TSNVEA3iSCXbxU0fElyrn363f4KfkIzSYYpiOLa5Tu0Op2P+j0qPRji9/ohaZV4hW/yoE5JB+C12J4Asaz/S2j9RgJ2OBrkpnTgZ3ouuEVllBepfVa+K0HIKNUcwBfceiBKAR2znoWKVd1A3KKsG69obuNOzq9SmRNXt/8BTwCnSHbCpHamaLT0rUUs2Yaw8deQFzTPpSiY4X5TKo98t4RSni2FJiyQWO+cXQHvqiw0auExqJ/3lCllOOM+XsE/ZHtUoaGb6HrsHvY='
    password: '{cipher}AQBgr1Y7BgFS68uq5Upq5cVPTcYBBjhvjES/OKZMP5JPo/2sOUsSScu/0CaZKQn/5tCj1O98BNzLSVDKXxbjE2lsyZd1zFc3sgFq3+7bwiigLlFC70SsPuvOOvz818OVfXgfYIVDaAI+dWoNNEg1vd9SmZRYLu24TuWjOHFuFrinmhVWsHNVnrlKsS4RIPIU8JfA/IU0iruE18n9DhQiIbwklFAPE5HBdfFEear/8rKhKT3niXGwJTaola8VfZnLHomR6Q5GQl4VDD843FBGuOk3j4Raec7NYe5c1yogJOLMsfd9ih078mSqddk9llI5fkb9k/UzwmMVgVlOB1ZYopCDwikOn11cqmWx45zLRDVVNx1HoV2WSDBYvTZyj3Wnmhg='

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  logging:
    level:
      org.hibernate.SQL: debug
      type: trace

  mail:
    username: '{cipher}AQBS38Q80l/gNzBsPhbhV+zmyT899kM5m6LZmmBdkVPQT2OG/kl+x/4KJpybrLnemWbb+YA/QOJv08Qa2nKWgD9SyK+7XdsILkxDsjmF6+F97VtoKvueO7fg7s3jEDBljgnEnfyqc6yPsmU9Sut/8v3TtqEpP/5OUjo56otrgyANz3ym2ubGlmCcFC+qNA4Y54M7+LFLS2wgCay8XH4pBRc/ofsgr5ka0emR35MM7+okf77B0FsIOEhgUPs3zUEPLRp2v7XTr8s8vUWLCXpbEMZNMi8B7BAVBQlM1taLNwh6e4RnttII3DmCYH6LTq/yEF6MxZ+gjHDhTQEBDZHuAB04J292hu5H+HbNq6tqLrhlYi2BNQCIO3HX2Lur5ulIKK3QysFNkwuakdF5UgBBew0s'
    password: '{cipher}AQA3Z4NGVbz06qNx5t2HfsSiMSipnnbdeHuBFBBYhJfLwzDrv8GnMfaIn1HrmZjSdmgsJHJwqUqaxJPSqlk1n3vH5ft/bO+2H1uS60/bBkb30z5o3BNk6yYvW+K52nJqMoY8rxL/GjLwGMB0ZCGGBAenhmWQrjgsq1Da7IkZk2N4NuAL7PiQJsxCIw7iBH4XfHVEMKEBJRZn5ax8+0FlWWYIGNEoaYbu+zKqb/OHgGx0ddTI+TGqQjcR+T+zNgzE43zDd8sP9E+QOKmZQqUz9yfcmmfCnmgOLqQeUhAcf6GSZPKbRtj8o0bGTC0js2YLfQZfhOsdiAe9IxJAatXZy4Q8PICK1j6pdraN7c5+pzLvhgpoWB6rAeHQ6skhrUPfiU4='