spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9c108.p.ssafy.io:3306/jutopia?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # url: jdbc:mysql://mysql-master:3306/jutopia?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: '{cipher}AQAoXMrKBup6aaYCg0wU+tDBVcvTpIg42opco+oqRNUrL1UdnWNDjPBE2tvIt17xYt4QkJGzoXEHG7J+mSi4Nv3ir3Y8t0C3PSPwzP44WULcM3Ni35nW9TSNVEA3iSCXbxU0fElyrn363f4KfkIzSYYpiOLa5Tu0Op2P+j0qPRji9/ohaZV4hW/yoE5JB+C12J4Asaz/S2j9RgJ2OBrkpnTgZ3ouuEVllBepfVa+K0HIKNUcwBfceiBKAR2znoWKVd1A3KKsG69obuNOzq9SmRNXt/8BTwCnSHbCpHamaLT0rUUs2Yaw8deQFzTPpSiY4X5TKo98t4RSni2FJiyQWO+cXQHvqiw0auExqJ/3lCllOOM+XsE/ZHtUoaGb6HrsHvY='
    password: '{cipher}AQBgr1Y7BgFS68uq5Upq5cVPTcYBBjhvjES/OKZMP5JPo/2sOUsSScu/0CaZKQn/5tCj1O98BNzLSVDKXxbjE2lsyZd1zFc3sgFq3+7bwiigLlFC70SsPuvOOvz818OVfXgfYIVDaAI+dWoNNEg1vd9SmZRYLu24TuWjOHFuFrinmhVWsHNVnrlKsS4RIPIU8JfA/IU0iruE18n9DhQiIbwklFAPE5HBdfFEear/8rKhKT3niXGwJTaola8VfZnLHomR6Q5GQl4VDD843FBGuOk3j4Raec7NYe5c1yogJOLMsfd9ih078mSqddk9llI5fkb9k/UzwmMVgVlOB1ZYopCDwikOn11cqmWx45zLRDVVNx1HoV2WSDBYvTZyj3Wnmhg='

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
      org.hibernate.SQL: debug
      type: trace

  mail:
    username: '{cipher}AQArncOMYqDwZJIhB0cYjBB4jCTAbUNvLoyepOlxFUhhu7hHRPcUswLlYyFdZp7eSsQNN4SVVZ3P9GM/h9aPYQBkgqQ59wlhN3CYXC0m0J9BySac7PcEhJFO4VkMuctjSjHgeBmgn9GHTRT0/2xt9BcLh7jXEtxEuAy5bpOjsxDn0mYVyYCwG0oroHmzgmaCW0fq153nOzXhShPxryoFvMiegVnYFALFv7Mr9VDpl9uZv5FzMXG4PVucTHLRCsIS1cGrxjl83k+iTCLK44LlbxvJb82rbTVI7OPRBkMXLxE4MIBzz27/jqpbjEXvnAPowjz8bd+P81YZ3IoXXEQ6xOmocI9x6W7wcOgfrf53S9mNJ0dMT0Y3pCRUx4Jze2NqyyWV9f99xN6UMCBkZcgGxRJP'
    password: '{cipher}AQBRHciKf6QGjXCzhJ1q/J/LPkuarCeD2SS8YhEbUbqai11nHG5DNN2w9Eeqv78+7dQxA1ILbGt/QtP19eW+QyKC2dXX8MlXQfyzuUZj6/zYolUkWOHbtsJLPOnRF9cE1NxroD61PctICZ7kCLsyL5WDOIHGzs8md7FBZHynOzA/LSgOQNBC437adfgHbeDZIB9b3cqAoC0vfufCNEjnmRz3447VC03qxMCTzX1FUb9pzi5WS8FSkL1QmctRS3PvR/63UjvQIG1Kj9muFDVq3znAQZPi5w030uJqKwc1GgsPaaMJQier1sUtcyTKA62U/mnE18XjKvAivX/AR+OmKOHlUUCeHzYyawynFFxAfBTdWrfHP+s7gqO2pZfB4sYJRjk='

gateway:
  ip: 172.18.0.7