spring:
  datasource:
    url: jdbc:mysql://j9c108.p.ssafy.io:3306/rentdb?serverTimezone=UTC
    username: rent
    password: rent
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 'update' is for development. Use 'validate' for production.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        

  # data:
  #   redis:
  #     url: redis://j9c108.p.ssafy.io:46379/

  kafka:
    bootstrapServers:
      - http://j9c108.p.ssafy.io:9092
      - http://j9c108.p.ssafy.io:9093
      - http://j9c108.p.ssafy.io:9094
# jutopia-network의 apigateway ip address로 변경
gateway:
  ip: 172.18.0.10
