spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none # 'update' is for development. Use 'validate' for production.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      cluster:
        nodes:
          - j9c108.p.ssafy.io:7001
          - j9c108.p.ssafy.io:7002
          - j9c108.p.ssafy.io:7003
          - j9c108.p.ssafy.io:7004
          - j9c108.p.ssafy.io:7005
          - j9c108.p.ssafy.io:7006
